backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    create: true
    folder: "content/blog"
    slug: "{{slug}}"
    path: "{{slug}}/index"
    editor:
      preview: true
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: "image",
          required: true,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
